---
- name: "Update Packages"
  become: true
  apt:
    update_cache: yes
#------------------------------------------------------------------------
- name: "Upgrade Packages"
  become: true
  apt:
    upgrade: true
#------------------------------------------------------------------------
- name: "install deps"
  become: true
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes
#------------------------------------------------------------------------
- name: "install pmg"
  become: true
  npm:
    name: "pm2"
    global: yes
    state: latest
#------------------------------------------------------------------------
- name: "Create Web folder"
  file: 
    path: "~/web"
    state: directory
#------------------------------------------------------------------------
- name: "Copy files"
  template:
    src: "index.js"
    dest: "~/web/index.js"
#------------------------------------------------------------------------
- name: "start application"
  shell: "pm2 start ~/web/index.js -f"
